package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/UNKNOWN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x86_64/jdk8u291/1294/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, April 8, 2021 2:17:41 AM BST
*/

public interface UNKNOWN
{

  /**
     * XXX
     */
  public static final short value = (short)(5);
}
